[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[variables]
VITE_ALCHEMY_API_KEY = "${VITE_ALCHEMY_API_KEY}"

[start]
cmd = "npx serve dist -s -l ${PORT:-3000}"
